# Generated by Django 4.0.6 on 2022-08-15 21:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Tarjetas', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tarjeta',
            old_name='xpiration_date',
            new_name='expiration_date',
        ),
    ]
