# Generated by Django 4.1 on 2022-08-15 22:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Tarjetas', '0002_rename_xpiration_date_tarjeta_expiration_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tarjeta',
            old_name='expiration_date',
            new_name='xpiration_date',
        ),
    ]
